[package]
name = "interface"
version = { workspace = true }
edition = { workspace = true }

[features]
cosmwasm_compat = []

[dependencies]
cosmwasm-std = { workspace = true }
cosmwasm-schema = { workspace = true }
