[package]
name = "adapter-interface"
version = { workspace = true }
edition = { workspace = true }
authors = ["Hydro Protocol"]

[lib]
crate-type = ["rlib"]

[dependencies]
cosmwasm-std = { workspace = true }
cosmwasm-schema = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
